[project]
name = "arboris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "html5lib>=1.1",
    "lxml>=6.0.1",
    "numpy>=2.0.2",
    "psutil>=7.0.0",
    "selectolax>=0.3.34",
]
